"""Public contract-kernel primitives."""

from .canonical import (
    IJSON_MAX_INTEGER,
    IJSON_MIN_INTEGER,
    MAX_NESTING,
    PROFILE_ID,
    CanonicalValueIntegrityError,
    ParsedCanonicalValue,
    build_canonical_value,
    canonical_bytes,
    canonical_sha256,
    parse_canonical_json,
    record_content_hash,
    record_hash_projection_bytes,
)
from .catalog_validation import (
    CatalogProfileConstraints,
    RawContractAssetBinding,
    build_catalog_profile_constraints,
    validate_m1_contract_requirement_set_intrinsic,
    validate_typed_terminal_result_catalog_constraints,
)
from .code_policy_validation import (
    KernelValidationPolicyConstraints,
    build_kernel_validation_policy_constraints,
    validate_emitted_diagnostic_registration,
    validate_stable_code_catalog_intrinsic,
    validate_typed_terminal_result_kernel_constraints,
)
from .code_policy_v1_1_validation import (
    KernelValidationPolicyV11Constraints,
    build_kernel_validation_policy_v1_1_constraints,
    validate_emitted_diagnostic_registration_v1_1,
    validate_stable_code_catalog_v1_1_intrinsic,
)
from .diagnostics import Diagnostic, DiagnosticCode
from .planning_validation import (
    PlanningScopeChain,
    PlanningScopeChainDeclaration,
    ScopeRevisionImpact,
    ScopeRevisionLineageProjection,
    build_planning_scope_chain_declaration,
    compute_scope_revision_impact,
    validate_agentization_plan,
    validate_frozen_inventory_scope,
    validate_inventory_discovery_result,
    validate_paper_source_snapshot,
    validate_planning_scope_chain,
    validate_planning_terminal_constraints,
    validate_scope_freeze_decision,
)
from .references import (
    SuppliedAsset,
    raw_asset_sha256,
    resolve_exact_asset_ref,
    resolve_exact_component_ref,
    resolve_exact_record_ref,
    validate_immutable_envelope,
    validate_immutable_record,
)
from .registry import (
    ContractSchemaRegistry,
    SchemaAssetBinding,
    build_schema_registry,
)
from .schema_validation import validate_immutable_record_payload
from .terminal_validation import validate_typed_terminal_result_intrinsic

__all__ = [
    "CatalogProfileConstraints",
    "KernelValidationPolicyConstraints",
    "KernelValidationPolicyV11Constraints",
    "build_kernel_validation_policy_v1_1_constraints",
    "validate_emitted_diagnostic_registration_v1_1",
    "validate_stable_code_catalog_v1_1_intrinsic",
    "PlanningScopeChain",
    "PlanningScopeChainDeclaration",
    "ScopeRevisionImpact",
    "ScopeRevisionLineageProjection",
    "build_planning_scope_chain_declaration",
    "compute_scope_revision_impact",
    "validate_agentization_plan",
    "validate_frozen_inventory_scope",
    "validate_inventory_discovery_result",
    "validate_paper_source_snapshot",
    "validate_planning_scope_chain",
    "validate_planning_terminal_constraints",
    "validate_scope_freeze_decision",
    "build_kernel_validation_policy_constraints",
    "validate_emitted_diagnostic_registration",
    "validate_stable_code_catalog_intrinsic",
    "validate_typed_terminal_result_kernel_constraints",
    "RawContractAssetBinding",
    "build_catalog_profile_constraints",
    "validate_m1_contract_requirement_set_intrinsic",
    "validate_typed_terminal_result_catalog_constraints",
    "Diagnostic",
    "DiagnosticCode",
    "IJSON_MAX_INTEGER",
    "IJSON_MIN_INTEGER",
    "MAX_NESTING",
    "PROFILE_ID",
    "CanonicalValueIntegrityError",
    "ParsedCanonicalValue",
    "build_canonical_value",
    "canonical_bytes",
    "canonical_sha256",
    "parse_canonical_json",
    "record_content_hash",
    "record_hash_projection_bytes",
    "SuppliedAsset",
    "raw_asset_sha256",
    "resolve_exact_asset_ref",
    "resolve_exact_component_ref",
    "resolve_exact_record_ref",
    "validate_immutable_envelope",
    "validate_immutable_record",
    "ContractSchemaRegistry",
    "SchemaAssetBinding",
    "build_schema_registry",
    "validate_immutable_record_payload",
    "validate_typed_terminal_result_intrinsic",
]
