module

public import AgtXIvRootMath.GottesmanCharacterDimension
public import Mathlib.Data.Fintype.BigOperators
public import Mathlib.Data.ZMod.Basic

/-!
# A finite binary Pauli-frame interface

This module isolates the exact step from a rank-`n` binary frame to the
delta-shaped character used by the Gottesman fixed-space argument.

`RankPauliFrame` is deliberately a downstream interface.  A later physical
Pauli module must still construct its binary word map from independent
commuting signed Pauli generators, prove that independence makes the map
injective, prove that the chosen subgroup is generated by its image, and prove
the tracelessness field from the concrete matrix evaluation.  In particular,
the structure does not contain the group cardinality, the delta-character
conclusion, or the dimension-one conclusion as fields.
-/

@[expose] public section

namespace AgtXIv.Gottesman

open Representation Classical

/-- The multiplicative form of `n` binary generator labels. -/
abbrev BinaryFrameGroup (n : ℕ) : Type :=
  Multiplicative (Fin n → ZMod 2)

/-- The concrete `2^n`-dimensional complex carrier used by an `n`-qubit frame. -/
abbrev QubitHilbert (n : ℕ) : Type :=
  Fin (2 ^ n) → ℂ

/--
An exact finite-binary interface for a rank-`n` Pauli frame.

The word map and its injectivity/surjectivity fields expose the still-separate
generator-independence and generation obligations.  `nonidentity_traceless`
records the still-separate concrete Pauli trace theorem.  None of these
obligations is silently replaced by the desired character or fixed-space
result.  In a phase-aware Pauli implementation this field may be constructed
only after proving that the stabilizer subgroup has no nontrivial scalar
element: the blanket statement that every nonidentity element of the full
Pauli group is traceless is false for `-I` and `±iI`.
-/
structure RankPauliFrame (n : ℕ) (S : Type) [Group S] [Fintype S] where
  word : BinaryFrameGroup n →* S
  word_injective : Function.Injective word
  word_surjective : Function.Surjective word
  action : Representation ℂ S (QubitHilbert n)
  nonidentity_traceless :
    ∀ s : S, s ≠ 1 → LinearMap.trace ℂ (QubitHilbert n) (action s) = 0

namespace RankPauliFrame

variable {n : ℕ} {S : Type} [Group S] [Fintype S]

/-- Package the frame action as a finite-dimensional representation. -/
noncomputable abbrev fdRep (F : RankPauliFrame n S) : FDRep ℂ S :=
  FDRep.of F.action

/-- The source-aligned generation and independence fields induce a binary
labelling equivalence; the equivalence itself is not assumed. -/
noncomputable def labelEquiv (F : RankPauliFrame n S) :
    BinaryFrameGroup n ≃* S :=
  MulEquiv.ofBijective F.word ⟨F.word_injective, F.word_surjective⟩

/-- The binary label group has exactly `2^n` elements. -/
theorem binaryFrameGroup_card (n : ℕ) :
    Fintype.card (BinaryFrameGroup n) = 2 ^ n := by
  simp [BinaryFrameGroup]

/-- Frame cardinality is derived from the binary labelling equivalence. -/
theorem card_eq_two_pow (F : RankPauliFrame n S) :
    Fintype.card S = 2 ^ n := by
  calc
    Fintype.card S = Fintype.card (BinaryFrameGroup n) :=
      (Fintype.card_congr F.labelEquiv.toEquiv).symm
    _ = 2 ^ n := binaryFrameGroup_card n

/-- Commutativity of the represented subgroup is derived from the surjective
binary word map rather than added as a separate conclusion-shaped field. -/
theorem elements_commute (F : RankPauliFrame n S) (s t : S) :
    Commute s t := by
  obtain ⟨a, rfl⟩ := F.word_surjective s
  obtain ⟨b, rfl⟩ := F.word_surjective t
  change F.word a * F.word b = F.word b * F.word a
  rw [← F.word.map_mul, mul_comm, F.word.map_mul]

/-- A nonidentity frame element has zero character. -/
theorem character_eq_zero_of_ne_one (F : RankPauliFrame n S) (s : S)
    (hs : s ≠ 1) :
    F.fdRep.character s = 0 := by
  simpa [fdRep, FDRep.character] using F.nonidentity_traceless s hs

/-- The character at the identity is the concrete Hilbert-space dimension. -/
theorem character_one_eq_two_pow (F : RankPauliFrame n S) :
    F.fdRep.character 1 = (2 ^ n : ℂ) := by
  rw [FDRep.char_one]
  simp [fdRep, QubitHilbert]

/-- The frame character is the group-cardinality delta function. -/
theorem character_delta (F : RankPauliFrame n S) (s : S) :
    F.fdRep.character s =
      if s = 1 then (Fintype.card S : ℂ) else 0 := by
  by_cases hs : s = 1
  · subst s
    rw [character_one_eq_two_pow]
    simp only [if_pos]
    exact_mod_cast (card_eq_two_pow F).symm
  · rw [if_neg hs]
    exact character_eq_zero_of_ne_one F s hs

/-- A rank-`n` binary Pauli frame has a one-dimensional common fixed space. -/
theorem finrank_commonFixed_eq_one (F : RankPauliFrame n S) :
    Module.finrank ℂ (commonFixedSpace F.fdRep.ρ) = 1 := by
  classical
  letI : Invertible (Fintype.card S : ℂ) :=
    invertibleOfNonzero (Nat.cast_ne_zero.mpr Fintype.card_ne_zero)
  exact finrank_commonFixed_eq_one_of_character_delta F.fdRep F.character_delta

end RankPauliFrame

end AgtXIv.Gottesman
