"""Executable source-to-chain evidence pipeline for the 2607.26154 migration case.

This is an explicit candidate-case replay. It does not pretend that the historical
graph was generated by a new model, or that a calibration curve already exists.
"""
from __future__ import annotations

import argparse
from collections import Counter, deque
import json
import pathlib
import platform
import sys
import uuid

from case import import_case, query_ids
from core import PlanLedger, VERSION, canonical, derive_state, digest, utcnow, write_json
from graph import prune_graph
from ingest import extract_paper, normalize_paper_id, resolve_external_identifiers
from lean import audit_projects, composition_witness
from model import extract_candidates
from model_routing import freeze_model_routing
from roots import audit_roots, junk_value_lint

REPO = pathlib.Path(__file__).resolve().parents[2]
BINDINGS = {
    "claim:perfect-graph-definition": [("AgtXIv.GraphFoundation.IsPerfect", "DEFINITION")],
    "claim:mwis-definition": [("AgtXIv.GraphFoundation.independentFinsets", "DEFINITION"),
                              ("AgtXIv.GraphFoundation.maxWeightIndependent", "DEFINITION")],
    "claim:sign-alignment-identity": [("AgtXIv.Stabilizerness.max_abs_signed_sum", "PROOF"),
                                     ("AgtXIv.Stabilizerness.max_abs_admissible_signed_sum_of_sign_set_eq", "BRIDGE")],
}


def _program_snapshot():
    return {str(p.relative_to(REPO)): digest(p.read_bytes())
            for p in sorted(pathlib.Path(__file__).parent.glob("*.py"))}


def _record_issues(ledger, rows, subject):
    for row in rows:
        ledger.issue(row.get("code", row.get("kind", "UNCLASSIFIED_ISSUE")),
                     row.get("subject", subject), row.get("detail", json.dumps(row, ensure_ascii=False)), row.get("evidence"))


def _artifact_ref(path):
    path = pathlib.Path(path)
    raw = path.read_bytes()
    return {"path": str(path), "sha256": digest(raw), "byte_size": len(raw)}


def _anchor_audit(papers):
    rows = []
    for paper in papers:
        for anchor in paper["anchors"]:
            resolved = anchor.get("resolution", "").startswith("RESOLVED")
            pending = anchor.get("exclusion", "").startswith("PENDING_")
            final_exclusion = bool(anchor.get("exclusion")) and not pending
            covered = bool(anchor.get("support_edge_ids")) or final_exclusion
            if resolved and not covered:
                rows.append({"anchor_id": anchor["id"], "paper_id": paper["paper"]["id"],
                             "source": anchor["source"], "failure": "RESOLVED_ANCHOR_WITHOUT_CHECKED_SUPPORT_OR_EXCLUSION"})
    return {"status": "FAILED" if rows else "RECORDED", "missing_classifications": rows,
            "scope": "RESOLVED_REFERENCE_ANCHORS_IN_FROZEN_SOURCE", "pending_is_exclusion": False}


def _terminal_records(graph, papers):
    by_id = {n["id"]: n for n in graph["nodes"]}
    frozen_papers = {paper["paper"]["id"]: paper for paper in papers if paper.get("source_files")}
    terminals = []
    for root in graph["roots"]:
        node_id = root["id"]
        node = by_id[node_id]
        paper = frozen_papers.get(node.get("paper_id"))
        source_available = bool(paper and node.get("paper_id", "").startswith("arxiv:"))
        # No inferential shortcut from root degree, old age, or a textbook label
        # to an exhausted search or from an arXiv ID to source availability.
        terminals.append({"id": "terminal:" + node_id, "node_id": node_id,
                          "terminal_kind": "ARXIV_SOURCE_AVAILABLE" if source_available else "FREE_TEXT_UNRESOLVED",
                          "terminal_kind_basis": "FROZEN_PAPER_SOURCE_PRESENT" if source_available else "NO_AUDITED_TERMINAL_CLASSIFICATION",
                          "source_manifest_sha256": paper["paper"].get("source_manifest_sha256") if paper else None,
                          "upstream_search": root["upstream_search"],
                          "search_evidence": (root.get("origin_evidence") or {}).get("references", []),
                          "library_binding": root.get("library_binding"),
                          "root_coverage_status": "ROOT_LIBRARY_AUDIT_NOT_RUN",
                          "subject_match_evidence": None, "blocked_by": root["blocked_by"]})
    return terminals


def _composition(graph, lean):
    rows = []
    for edge in graph["edges"]:
        upstream, downstream = edge["from"], edge["to"]
        row = {"edge_id": edge["id"], "support_group_id": edge["support_group_id"],
               "upstream": upstream, "downstream": downstream, "witnesses": [],
               "status": "MISSING_DECLARATION_BINDING", "binding_alignment": "CANDIDATE_UNREVIEWED"}
        if upstream in BINDINGS and downstream in BINDINGS:
            witnesses = [composition_witness(lean["records"], u[0], v[0])
                         for u in BINDINGS[upstream] for v in BINDINGS[downstream]]
            row.update(witnesses=witnesses,
                       status="COMPOSED" if any(w["status"] == "COMPOSED" for w in witnesses) else "NOT_COMPOSED")
        rows.append(row)
    return rows


def _stage_coverage(anchor_audit, lean):
    # Numbering links back to the design; it is not a claim that all phases run.
    return [
        {"phase": 0, "status": "PARTIAL", "artifact": "query-source-spans.json",
         "remaining": "Resolve missing legacy query spans and freeze their scientific meaning."},
        {"phase": 1, "status": "PARTIAL", "artifact": "papers/",
         "remaining": "Complete semantic extraction and checked occurrence-to-claim identity mapping."},
        {"phase": 2, "status": "FAILED_ANCHOR_AUDIT" if anchor_audit["missing_classifications"] else "PARTIAL",
         "artifact": "anchor-audit.json", "remaining": "Classify mathematical support and typed exclusions for every resolved anchor."},
        {"phase": 3, "status": "PARTIAL", "artifact": "identifier-search/",
         "remaining": "Resolve remaining identities, authenticated ADS fallback, and source-subject matching."},
        {"phase": 4, "status": "NOT_IMPLEMENTED", "artifact": None,
         "remaining": "Admit newly discovered support with calibrated decisions and plan-budget gates."},
        {"phase": 5, "status": "LEGACY_FRONTIER_ONLY", "artifact": "papers/",
         "remaining": "Recurse over newly admitted support; the current queue only visits imported legacy leads."},
        {"phase": 6, "status": "EXECUTED_ON_LEGACY_CANDIDATES", "artifact": "graph.json",
         "remaining": "Re-prune after new checked dependency admissions; supply measured route costs."},
        {"phase": 7, "status": "CANDIDATE_BINDING_AUDIT_ONLY", "artifact": "root-audit.json",
         "remaining": "Resolve missing bindings and judge exact source coverage before proof funding."},
        {"phase": 8, "status": "NOT_RUN", "artifact": None,
         "remaining": "Render each unsupported root as a faithful explicit premise and run junk-value lint."},
        {"phase": 9, "status": "GATED_NOT_ATTEMPTED", "artifact": "formalization-queue.json",
         "remaining": "Run bounded source-aligned Lamport/Lean proof attempts and nonvacuity checks."},
        {"phase": 10, "status": "PARTIAL" if lean["records"] else "NOT_RUN", "artifact": "composition.json",
         "remaining": "Bind every required endpoint and extract composition witnesses for the query chain."},
        {"phase": 11, "status": "INCOMPLETE_CERTIFICATE_EMITTED", "artifact": "chain-certificate.json",
         "remaining": "Construct and check a composed query declaration, then read its explicit premise list from Lean."},
    ]


def _certificate(ledger, graph, lean, terminals, anchor_audit, stages):
    # Only declarations bound to the actual query can supply the chain's premise
    # list. Pooling unrelated hypotheses from a package would invent a theorem.
    missing = ["QUERY_DECLARATION_NOT_CONSTRUCTED", "SEMANTIC_EXTRACTION_NOT_COMPLETE",
               "AUTOMATIC_DEPENDENCY_GATES_NOT_CALIBRATED", "EARLIEST_ORIGIN_SEARCH_NOT_EXHAUSTED",
               "MATHLIB_PHYSLIB_COMMON_ENVIRONMENT_NOT_ESTABLISHED",
               "RECURSIVE_NEW_SUPPORT_ADMISSION_NOT_IMPLEMENTED", "ROOT_LIBRARY_COVERAGE_NOT_SOURCE_ALIGNED",
               "UNSUPPORTED_ROOT_PREMISES_NOT_RENDERED", "BOTTOM_UP_FORMALIZATION_NOT_ATTEMPTED"]
    if anchor_audit["missing_classifications"]:
        missing.append("RESOLVED_ANCHOR_RECALL_AUDIT_FAILED")
    if graph["conditional_nodes"]:
        missing.append("SUPPORT_BLOCKERS_REMAIN")
    scope = "QUERY_CANDIDATE_GRAPH:" + digest(canonical(graph["query_ids"]))
    theorem_ids = [n["id"] for n in graph["nodes"] if n["kind"] in {"theorem", "lemma", "proposition", "corollary"}]
    definition_ids = [n["id"] for n in graph["nodes"] if n["kind"] == "definition"]
    return {"kind": "ChainCertificate", "contract_version": VERSION, "plan_id": ledger.plan["plan_id"],
            "state": "CHAIN_INCOMPLETE", "query_ids": graph["query_ids"], "query_declarations": [],
            "environment_sha256": lean.get("environment", {}).get("sha256"),
            "premise_extraction_status": "QUERY_DECLARATION_ABSENT",
            "premises_from_lean_environment": [],
            "terminal_kind_counts": {"scope": scope + ":GRAPH_ROOTS_NOT_LEAN_PREMISES", "counts": dict(Counter(t["terminal_kind"] for t in terminals))},
            "coverage": [
                {"scope": scope + ":THEOREM_CANDIDATES", "metric": "SOURCE_ALIGNED_PROOF_DISCHARGED", "eligible": len(theorem_ids), "proof_discharged": 0},
                {"scope": scope + ":DEFINITION_CANDIDATES", "metric": "SOURCE_ALIGNED_STATEMENT_DISCHARGED", "eligible": len(definition_ids), "statement_discharged": 0}],
            "stage_coverage": stages,
            "missing_obligations": missing, "source_completeness_asserted": False, "human_accepted": False,
            "headline": "CHAIN_INCOMPLETE: no composed query declaration; a conditional implication has not yet been kernel checked."}


def _project_cypher(graph, plan_id):
    # Parameters are JSON data; no source text is interpolated into Cypher.
    query = (
        "UNWIND $nodes AS n MERGE (c:ResearchCandidate {plan_id:$plan_id, id:n.id}) "
        "SET c.kind=n.kind, c.disposition=n.disposition;\n"
        "UNWIND $groups AS g MERGE (s:SupportGroup {plan_id:$plan_id,id:g.id}) "
        "SET s.target=g.target, s.members=g.members, s.disposition=g.disposition;\n"
        "UNWIND $groups AS g MATCH (s:SupportGroup {plan_id:$plan_id,id:g.id}) "
        "MATCH (t:ResearchCandidate {plan_id:$plan_id,id:g.target}) MERGE (s)-[:SUPPORTS]->(t) "
        "WITH g,s UNWIND g.members AS member "
        "MATCH (u:ResearchCandidate {plan_id:$plan_id,id:member}) MERGE (u)-[:JOINT_PREMISE]->(s);\n")
    return query, {"plan_id": plan_id, "nodes": [{k: n[k] for k in ("id", "kind", "disposition")} for n in graph["nodes"]],
                   "groups": graph["support_groups"]}


def run(output, *, query="all", model_calls=False, lean_builds=False, network=False, model_evidence=None, lean_evidence=None):
    output = pathlib.Path(output).resolve()
    if output.exists() and any(output.iterdir()):
        raise ValueError("Use a new run directory; earlier run evidence is immutable")
    output.mkdir(parents=True, exist_ok=True)
    case = import_case(REPO)
    queries = query_ids(case, query)
    plan = {"contract_version": VERSION, "plan_id": "plan:" + uuid.uuid4().hex,
            "paper_id": case["target_paper_id"], "query_ids": queries, "created_at": utcnow(),
            "cost_mode": "ACCOUNT_QUOTA", "limits": {"max_model_calls": 8, "max_cost_microusd": 0,
                "max_papers": 12, "no_progress_limit": 2, "max_call_seconds": 360, "max_node_attempts": 3},
            "environment": {"python": platform.python_version(), "host_sources": _program_snapshot(),
                            "model_routing": freeze_model_routing(),
                            "mode": "EXPLICIT_LEGACY_CASE_REPLAY_CANDIDATES_ONLY"}, "source_sha256": case["source_sha256"]}
    ledger = PlanLedger(output, plan)
    write_json(output / "plan.json", plan)
    _record_issues(ledger, case["issues"], case["target_paper_id"])
    with ledger.stage("00.freeze", plan) as receipt:
        receipt["frozen_query_spans"] = {n["id"]: n["source_spans"] for n in case["nodes"] if n["id"] in queries}
        frozen_artifact = write_json(output / "query-source-spans.json", dict(receipt))
        receipt["artifact"] = frozen_artifact
        receipt["migration_input"] = write_json(output / "case-input.json", case)
    with ledger.stage("06.prune_continuously", case) as receipt:
        graph = prune_graph(case["nodes"], case["support_groups"], queries)
        receipt["graph"] = write_json(output / "graph.json", graph)
        focus = prune_graph(case["nodes"], case["support_groups"], ["claim:closed-form-rom"])
        receipt["closed_form_branch"] = write_json(output / "closed-form-branch.json", focus)
        receipt["execution_scope"] = "INITIAL_LEGACY_GRAPH_ONLY; NO_NEW_SUPPORT_ADMISSIONS"
    _record_issues(ledger, graph["issues"], case["target_paper_id"])
    selected = set(graph["selected_node_ids"])
    leads = [case["target_paper_id"]]
    leads += sorted({n["paper_id"] for n in case["nodes"] if n["id"] in selected and n.get("paper_id") and n["paper_id"] != case["target_paper_id"]})
    frontier, papers, visited = deque(leads), [], set()
    model_budget_exhausted = False
    with ledger.stage("01-05.extract_references_frontier", {"case_leads": leads}) as receipt:
        receipt["paper_artifacts"] = []
        while frontier and len(visited) < plan["limits"]["max_papers"]:
            paper_id = frontier.popleft()
            if paper_id in visited:
                continue
            visited.add(paper_id)
            slug = paper_id.replace(":", "-").replace("/", "_")
            paper = extract_paper(REPO, paper_id, output / "papers" / slug)
            papers.append(paper)
            extraction_path = output / "papers" / slug / "extraction.json"
            # The unavailable-source path returns data without publishing a file.
            if not extraction_path.exists():
                write_json(extraction_path, paper)
            paper_artifacts = {"paper_id": paper_id, "extraction": _artifact_ref(extraction_path)}
            receipt["paper_artifacts"].append(paper_artifacts)
            print(f"EXTRACT {paper_id}: {len(paper['claims'])} occurrences", flush=True)
            _record_issues(ledger, paper["issues"], paper_id)
            identifiers = resolve_external_identifiers(paper, output / "identifier-search" / slug,
                                                       enable_network=network, max_requests=5)
            paper_artifacts["identifier_search"] = write_json(output / "identifier-search" / slug / "result.json", identifiers)
            _record_issues(ledger, identifiers["issues"], paper_id)
            for item in identifiers["records"]:
                if item["search_status"] != "SEARCH_EXHAUSTED":
                    ledger.issue("IDENTIFIER_FRONTIER", item["bibliography_id"],
                                 "Bibliographic resolution does not exhaust upstream theorem-origin search.", item)
            model_result = None
            if model_calls and not model_budget_exhausted and paper["claims"]:
                try:
                    model_result = extract_candidates(ledger, paper, output / "model")
                except RuntimeError as exc:
                    if str(exc) not in {"MODEL_CALL_BUDGET_EXHAUSTED", "MONETARY_BUDGET_EXHAUSTED"}:
                        raise
                    model_budget_exhausted = True
                    ledger.issue("MODEL_EXECUTION_HALTED_BY_BUDGET", paper_id, str(exc))
                if model_result is not None:
                    paper_artifacts["model_extraction"] = write_json(output / "model" / (slug + ".json"), model_result)
                if model_result and model_result["candidate"]:
                    # Self-reported candidates are published for inspection but
                    # do not pass the admission gate or rewrite the legacy graph.
                    ledger.issue("DECISION_CALIBRATION_REQUIRED", paper_id,
                                 "New candidate claims and dependencies await registered calibration or explicit human judgement.", model_result["receipt"]["call_id"])
                elif model_result:
                    ledger.issue("MODEL_EXTRACTION_FAILED", paper_id, model_result["receipt"]["error"] or "No candidate")
            if not ledger.progress(paper_id, len(paper["claims"])):
                ledger.issue("NO_PROGRESS_LIMIT_REACHED", paper_id,
                             "The plan's per-lead counter reached its limit; this lead will not be re-enqueued.")
        receipt.update(papers={"scope": "VISITED_LEGACY_SUPPORT_PAPER_LEADS", "count": len(papers)},
                       visited=sorted(visited), remaining_frontier=list(frontier),
                       model_budget_exhausted=model_budget_exhausted,
                       recursion_status="NO_NEW_SUPPORT_ADMISSION; LEGACY_FRONTIER_ONLY")
        if frontier:
            ledger.issue("PAPER_BUDGET_FRONTIER", case["target_paper_id"],
                         "The paper limit left legacy leads unexpanded; they remain FRONTIER.", list(frontier))
    if model_evidence:
        path = pathlib.Path(model_evidence).resolve()
        raw = path.read_bytes()
        imported = json.loads(raw)
        write_json(output / "imported-model-evidence.json", {"source": str(path), "sha256": digest(raw), "evidence": imported,
                   "use": "CANDIDATE_ONLY_SEPARATE_FROZEN_PLAN_NOT_AN_ADMISSION_DECISION"})
    anchor_audit = _anchor_audit(papers)
    write_json(output / "anchor-audit.json", anchor_audit)
    if anchor_audit["status"] == "FAILED":
        ledger.issue("ANCHOR_RECALL_AUDIT_FAILED", case["target_paper_id"],
                     f"{len(anchor_audit['missing_classifications'])} resolved references lack checked support or final exclusion.", "anchor-audit.json")
    terminals = _terminal_records(graph, papers)
    write_json(output / "terminals.json", terminals)
    for terminal in terminals:
        ledger.issue("ROOT_LIBRARY_COVERAGE_NOT_AUDITED", terminal["node_id"],
                     "No per-root exact declaration, library revision, and source-subject coverage audit has run.", terminal)
    with ledger.stage("07-10.lean_environment_and_composition", {"projects": ["AgtXIvRootMath", "AgtXIvVarela", "AgtXIvStabilizerness"]}) as receipt:
        if lean_evidence:
            path = pathlib.Path(lean_evidence).resolve()
            raw = path.read_bytes()
            lean = json.loads(raw)
            from lean import _snapshot
            if lean.get("environment", {}).get("sha256") != _snapshot(REPO)["sha256"]:
                raise ValueError("Imported Lean evidence no longer matches current source environment")
            write_json(output / "lean-evidence-import.json", {"path": str(path), "sha256": digest(raw)})
            write_json(output / "lean-audit.json", lean)
        else:
            lean = audit_projects(REPO, output / "lean", run_builds=lean_builds)
            write_json(output / "lean-audit.json", lean)
        composition = _composition(graph, lean)
        receipt["composition"] = write_json(output / "composition.json", composition)
        receipt["lean_audit"] = _artifact_ref(output / "lean-audit.json")
        receipt.update(execution_status=lean["execution_status"],
                       audited_declarations={"scope": "CURRENT_SELECTED_LEAN_DECLARATIONS", "count": len(lean["records"])},
                       graph_edge_binding_inventory={"scope": graph["scope"], "count": len(composition)},
                       graph_edges_audited={"scope": graph["scope"], "count": sum(bool(row["witnesses"]) for row in composition)},
                       formalization_status="NO_PROOF_ATTEMPTS; EXISTING_DECLARATIONS_ONLY")
    _record_issues(ledger, lean.get("issues", []), case["target_paper_id"])
    write_json(output / "root-audit.json", audit_roots(graph, lean))
    lint_path = REPO / "formal/AgtXIvVarela/AgtXIvVarela/ExternalPerfectGraphFoundation.lean"
    write_json(output / "junk-value-lint.json", junk_value_lint(lint_path.read_text(), requires_finite=True))
    for row in composition:
        if row["status"] != "COMPOSED":
            ledger.issue(row["status"], row["edge_id"],
                         "This support membership has no current composed declaration witness.", row)
    formalization_queue = []
    records = {r["declaration"]: r for r in lean["records"]}
    graph_nodes = {n["id"]: n for n in graph["nodes"]}
    component_members = {scc["id"]: scc["members"] for scc in graph["sccs"]}
    ordered_nodes = [node_id for component in graph["condensation_order"]
                     for node_id in component_members.get(component, [component])]
    for node_id in ordered_nodes:
        node = graph_nodes[node_id]
        bound = [{"declaration": d, "role": role, "environment_record": records.get(d)} for d, role in BINDINGS.get(node_id, [])]
        facts = {"blocked_by": node.get("blocked_by", []), "needs_review": True,
                 "cycle": node["formalization_state"] == "ROUTE_UNDETERMINED",
                 "source_read_defective": node.get("source_read_defective", False),
                 "source_unreachable": node.get("source_unreachable", False)}
        formalization_queue.append({"node_id": node_id, "bindings": bound, "derived_state": derive_state(facts),
                                    "structurally_schedulable": node_id in graph["formalization_order"],
                                    "blocked_by": node.get("blocked_by", []),
                                    "attempts": 0, "attempt_cap": plan["limits"]["max_node_attempts"],
                                    "required_outputs_missing": ["SOURCE_ALIGNED_LAMPORT_PROOF", "NONVACUITY_WITNESS", "CHECKED_SUPPORT_JUDGEMENTS"],
                                    "execution": "GATED_NOT_A_PROOF_ATTEMPT"})
    write_json(output / "formalization-queue.json", formalization_queue)
    stages = _stage_coverage(anchor_audit, lean)
    write_json(output / "stage-coverage.json", stages)
    for stage in stages:
        ledger.issue("DESIGN_PHASE_INCOMPLETE", "phase:" + str(stage["phase"]),
                     stage["remaining"], stage)
    certificate = _certificate(ledger, graph, lean, terminals, anchor_audit, stages)
    with ledger.stage("11.certify", {"graph": digest(canonical(graph)), "lean": digest(canonical(lean))}) as receipt:
        receipt["certificate"] = write_json(output / "chain-certificate.json", certificate)
    projection, parameters = _project_cypher(graph, plan["plan_id"])
    (output / "projection.cypher").write_text(projection)
    write_json(output / "projection-parameters.json", parameters)
    coverage = [row for p in papers for row in p["coverage"]]
    write_json(output / "source-coverage.json", coverage)
    write_json(output / "ledger.json", ledger.snapshot())
    report = (
        "# arXiv:2607.26154 schema v0.3 case run\n\n" + certificate["headline"] + "\n\n"
        f"The run visited {len(papers)} paper leads, froze source for {sum(bool(p.get('source_files')) for p in papers)} papers, "
        f"and extracted {sum(len(p['claims']) for p in papers)} automatic occurrences. "
        f"It selected {len(queries)} mathematical query candidates and {len(graph['selected_node_ids'])} graph nodes. "
        "These count different scopes and are not interchangeable.\n\n"
        f"The closed-form branch retains {len(focus['selected_node_ids'])} nodes. "
        f"The anchor audit leaves {len(anchor_audit['missing_classifications'])} resolved references without checked support judgements.\n\n"
        "The legacy graph is a candidate migration input. New source extraction does not validate its edges. "
        "All earliest-origin records remain FRONTIER until documented searches exhaust them. "
        "The formalization queue is gated; a missing proof was not replaced by an arbitrary-Prop tautology.\n\n"
        "This run covers the imported legacy frontier. It does not yet admit and recursively crawl newly inferred support. "
        "The per-phase implemented/remaining distinction is recorded in stage-coverage.json.\n\n"
        f"Current Lean audit: {lean['execution_status']}; {len(lean['records'])} declarations inspected. "
        "A current build proves only its formal declarations; no composed theorem states all query claims.\n\n"
        "## Remaining obligations\n\n" + "".join("- " + x + "\n" for x in certificate["missing_obligations"]))
    (output / "REPORT.md").write_text(report)
    print(certificate["headline"], flush=True)
    print(str(output / "REPORT.md"), flush=True)
    return certificate


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--paper", default="2607.26154v1")
    parser.add_argument("--query", default="all")
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--model", action="store_true", help="Make bounded actual extraction calls")
    parser.add_argument("--lean", action="store_true", help="Build and inspect current selected Lean environment")
    parser.add_argument("--network", action="store_true", help="Make bounded Crossref fallback requests")
    parser.add_argument("--model-evidence", type=pathlib.Path)
    parser.add_argument("--lean-evidence", type=pathlib.Path)
    args = parser.parse_args()
    if normalize_paper_id(args.paper) not in {"arxiv:2607.26154", "arxiv:2607.26154v1"}:
        parser.error("This runner is the explicit migration case; generic fresh-paper ingest is a separate interface")
    certificate = run(args.output, query=args.query, model_calls=args.model, lean_builds=args.lean,
                      network=args.network, model_evidence=args.model_evidence, lean_evidence=args.lean_evidence)
    return 0 if certificate["state"] == "CHAIN_CERTIFICATE_EMITTED" else 2


if __name__ == "__main__":
    raise SystemExit(main())
