#!/usr/bin/env python3
"""Generate report-only schema tables; never mutate the schema bundle.

Run from any directory. --check compares exact generated bytes without writing.
The source inventory and its digests are emitted alongside the TeX appendix.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
BUNDLE = ROOT / "schema v0.0"
OUTPUT = HERE / "generated"


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def escape(value: object) -> str:
    replacements = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    text = str(value).replace("\u2014", "---").replace("\u2013", "--").replace("\u2264", "<=").replace("\u2265", ">=")
    return "".join(replacements.get(char, char) for char in text)


def shape(node: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1].replace("common.schema.json#/$defs/", "")
    if "const" in node:
        return "constant " + str(node["const"])
    if "enum" in node:
        values = node["enum"]
        return "one of " + ", ".join(map(str, values)) if len(values) <= 10 else f"enum ({len(values)} exact values; see schema)"
    for keyword in ("anyOf", "oneOf", "allOf"):
        if keyword in node:
            return keyword + ": " + "; ".join(shape(child) for child in node[keyword] if shape(child))
    kind = node.get("type", "")
    if isinstance(kind, list):
        kind = " / ".join(kind)
    if kind == "array":
        return "array of " + shape(node.get("items", {}))
    if not kind and "properties" in node:
        return "constrained object"
    return kind


def limits(node: dict) -> str:
    names = ("minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems", "format", "uniqueItems")
    result = [f"{name}={node[name]}" for name in names if name in node]
    if "pattern" in node:
        result.append("pattern enforced (see schema)")
    if node.get("additionalProperties") is False:
        result.append("closed object")
    return "; ".join(result)


def fields(node: dict, prefix: str = ""):
    required = set(node.get("required", []))
    for name, child in node.get("properties", {}).items():
        path = prefix + name
        yield path, name in required, child
        if "properties" in child:
            yield from fields(child, path + ".")
        items = child.get("items", {})
        if isinstance(items, dict) and "properties" in items:
            yield from fields(items, path + "[].")


def table(node: dict) -> tuple[str, int]:
    rows = list(fields(node))
    lines = [r"\begin{longtable}{@{}P{0.27\linewidth}P{0.69\linewidth}@{}}", r"\toprule Field & Meaning and local constraints \\", r"\midrule\endfirsthead", r"\toprule Field & Meaning and local constraints (continued) \\", r"\midrule\endhead", r"\bottomrule\endfoot"]
    for name, required, child in rows:
        description = escape(child.get("description", "No separate field description in the bound schema."))
        detail = escape(shape(child))
        bound = escape(limits(child))
        flag = "required" if required else "optional"
        lines.append(r"\code{" + name + "} " + r"{\scriptsize (" + flag + r")} & " + description + r"\newline{\footnotesize\color{muted}" + detail + ("; " + bound if bound else "") + r"} \\")
    lines.append(r"\end{longtable}")
    return "\n".join(lines), len(rows)


def generate() -> dict[str, str]:
    inputs = {"catalog.json", "manifest.json", "common.schema.json"}
    catalog = json.loads((BUNDLE / "catalog.json").read_text())
    manifest = json.loads((BUNDLE / "manifest.json").read_text())
    common = json.loads((BUNDLE / "common.schema.json").read_text())
    family_count = len(catalog["records"])
    shared_count = len(common["$defs"])
    lines = ["% Generated by generate_appendix.py. Do not edit.", r"\section{Generated contract field reference}\label{app:fields}", "This appendix is generated from the exact experimental JSON Schema package. It documents all registered payload fields and shared structures. The envelope is shown once. Required markers are local to the containing object; conditional branches, exact regular expressions and extended enumerations remain defined by the original schemas. A field being present does not establish that its producer or scientific reviewer has been implemented.", r"The source manifest SHA-256 is \code{" + digest((BUNDLE / "manifest.json").read_bytes()) + "}. The report-side input inventory is stored in \\code{generated/schema-inputs.json}."]
    first = json.loads((BUNDLE / catalog["records"][0]["schema"]).read_text())
    envelope = {"properties": {k: v for k, v in first["properties"].items() if k != "payload"}, "required": first["required"]}
    envelope["properties"]["record_type"] = {"type": "string", "description": "The exact discriminator of this record family; its constant is specified by each family schema."}
    envelope["properties"]["payload"] = {"type": "object", "additionalProperties": False, "description": "Family-specific fields, documented separately for all registered record families below."}
    lines += [r"\subsection{Common record envelope}"]
    text, count = table(envelope)
    lines.append(text)
    total = count
    lines += [r"\clearpage\subsection{Shared value structures}"]
    for name, value in common["$defs"].items():
        lines.extend([r"\Needspace{14\baselineskip}\subsubsection{" + escape(name) + "}", escape(value.get("description", ""))])
        text, count = table(value)
        lines.append(text)
        total += count
    family_rows = []
    lines += [r"\clearpage\subsection{Record families and payloads}"]
    for record in catalog["records"]:
        name = record["schema"]
        inputs.add(name)
        value = json.loads((BUNDLE / name).read_text())
        lines += [r"\Needspace{14\baselineskip}\subsubsection{" + escape(record["title"]) + "}", escape(value.get("description", "")), r"\textbf{Schema:} \code{" + name + "}. " + r"\textbf{Roadmap:} " + escape(", ".join(record["roadmap_tasks"])) + "."]
        text, count = table(value["properties"]["payload"])
        lines.append(text)
        total += count
        family_rows.append({"record_type": record["record_type"], "schema": name, "title": record["title"], "payload_field_rows": count})
    input_records = [{"path": str((BUNDLE / name).relative_to(ROOT)), "sha256": digest((BUNDLE / name).read_bytes())} for name in sorted(inputs)]
    inventory = {"report_generator": "docs/technical-report/generate_appendix.py", "generator_version": "1.0.0", "generator_sha256": digest(Path(__file__).read_bytes()), "contract_version": manifest["contract_version"], "record_family_count": family_count, "shared_type_count": shared_count, "field_rows": total, "input_files": input_records, "record_families": family_rows}
    identity = "\n".join(["% Generated. Do not edit.", r"\newcommand{\RecordFamilyCount}{" + str(family_count) + "}", r"\newcommand{\SharedTypeCount}{" + str(shared_count) + "}", r"\newcommand{\ContractVersion}{" + escape(manifest["contract_version"]) + "}", r"\newcommand{\SchemaFieldCount}{" + str(total) + "}"]) + "\n"
    return {"schema-fields.tex": "\n\n".join(lines) + "\n", "schema-identity.tex": identity, "schema-inputs.json": json.dumps(inventory, indent=2, ensure_ascii=False) + "\n"}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = generate()
    if args.check:
        mismatches = [name for name, value in outputs.items() if not (OUTPUT / name).exists() or (OUTPUT / name).read_text() != value]
        if mismatches:
            raise SystemExit("Generated report appendix drift: " + ", ".join(mismatches))
        print("Report appendix is current (3 files).")
        return
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for name, value in outputs.items():
        (OUTPUT / name).write_text(value)
    print("Generated report appendix (3 files); source schemas unchanged.")


if __name__ == "__main__":
    main()
