"""Provisional source packages: static original bytes, no science execution."""
from __future__ import annotations

import copy
import hashlib
import io
from pathlib import Path
import subprocess
import sys
import tarfile

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'src'))
from agtxiv_v3.candidates import (CandidatePackage, _artifact, build_candidate_package,
    persist_candidate_package, query_candidate_package, robustness_proposals, ROBUSTNESS_QUESTIONS)
from agtxiv_v3.contracts import ContractError, SchemaBundle, SuppliedArtifact, canonical
from agtxiv_v3.intake import inspect_source_directory
from agtxiv_v3.source import SourceError
from agtxiv_v3.storage import LocalStore


@pytest.fixture(scope='module')
def bundle():
    return SchemaBundle()


@pytest.fixture
def inspection(tmp_path):
    root = tmp_path / 'source'
    root.mkdir()
    (root / 'main.tex').write_bytes('α\r\n% not a claim\n\\input{missing}\n\nlast'.encode())
    (root / 'unused.tex').write_bytes(b'unused')
    (root / 'empty.tex').write_bytes(b'')
    (root / 'figure.pdf').write_bytes(b'%PDF\x00\xff')
    (root / 'bad.tex').write_bytes(b'\xff')
    (root / 'build').mkdir()
    (root / 'build' / 'run.log').write_bytes(b'preexisting generated bytes')
    return inspect_source_directory(root, 'main.tex')


def proposal(inspection):
    data = inspection.sources['main.tex'][:2]
    return {'id': 'candidate', 'interpretation': 'Explicit synthetic test interpretation, not observed science.',
            'anchors': [{'path': 'main.tex', 'start_byte': 0, 'end_byte': 2, 'sha256': hashlib.sha256(data).hexdigest()}],
            'conditions': ['Unverified condition'], 'dependencies': [], 'unknowns': ['All science unverified']}


def test_full_denominator_segments_and_determinism(inspection):
    first = build_candidate_package(inspection)
    repeated = build_candidate_package(inspect_source_directory(inspection.root, 'main.tex'))
    assert first == repeated
    body = first.report()
    assert body['file_count'] == len(inspection.sources) == 6
    assert body['total_bytes'] == sum(map(len, inspection.sources.values()))
    files = {f['path']: f for f in body['files']}
    assert files['build/run.log']['origin'] == 'LOCAL_GENERATED_UNVERIFIED'
    assert files['bad.tex']['status'] == 'BYTES_ONLY_UNREVIEWED'
    assert files['empty.tex']['status'] == 'EMPTY_FILE'
    for path in ('main.tex', 'unused.tex'):
        segments = [s for s in body['segments'] if s['path'] == path]
        assert segments[0]['start_byte'] == 0
        assert segments[-1]['end_byte'] == len(inspection.sources[path])
        assert all(a['end_byte'] == b['start_byte'] for a, b in zip(segments, segments[1:]))
        assert b''.join(inspection.sources[path][s['start_byte']:s['end_byte']] for s in segments) == inspection.sources[path]
    assert 'MISSING_INCLUDE' in {x['code'] for x in body['issues']}
    assert not first.records


def test_proposals_bind_identity_and_reopen_exact_history(tmp_path, bundle, inspection):
    old = build_candidate_package(inspection, proposals=[proposal(inspection)])
    new = build_candidate_package(inspection, proposals=[proposal(inspection)], open_questions=['New explicit unknown'])
    assert old.reference() != new.reference()
    database = tmp_path / 'candidate.sqlite'
    with LocalStore(database, bundle) as store:
        assert persist_candidate_package(store, old).valid
        assert persist_candidate_package(store, old).valid
        assert persist_candidate_package(store, new).valid
        assert store.candidate_head('anything') is None
        assert store._db.execute('SELECT count(*) FROM records').fetchone() == (0,)
        assert store._db.execute('SELECT count(*) FROM candidate_heads').fetchone() == (0,)
    with LocalStore(database, bundle, readonly=True) as store:
        result = query_candidate_package(store, old.reference())
        assert result['package'] == old.report()
        assert result['mode'] == 'PROVISIONAL'
        assert result['scientific_assessment'] == 'NOT_PERFORMED'
        assert result['package']['proposals'][0]['data_class'] == 'ORACLE_PROPOSED'
        assert result['package']['proposals'][0]['verification'] == 'UNVERIFIED'
        assert result['open_questions'] != query_candidate_package(store, new.reference())['open_questions']
        for span in result['source_spans']:
            assert bytes.fromhex(span['bytes_hex']) == inspection.sources[span['path']][span['start_byte']:span['end_byte']]
        for change in ({'sha256': 'sha256:' + '0' * 64}, {'byte_size': True}, {'artifact_id': 'artifact:missing'}):
            with pytest.raises((ContractError, SourceError)):
                query_candidate_package(store, {**old.reference(), **change})


@pytest.mark.parametrize('change', ['span', 'path', 'dependency', 'label'])
def test_bad_proposals_rejected(inspection, change):
    p = proposal(inspection)
    if change == 'span': p['anchors'][0]['end_byte'] = 1
    if change == 'path': p['anchors'][0]['path'] = 'absent.tex'
    if change == 'dependency': p['dependencies'] = ['absent']
    if change == 'label': p['data_class'] = 'OBSERVED'
    with pytest.raises(SourceError):
        build_candidate_package(inspection, proposals=[p])


@pytest.mark.parametrize('change', ['omitted_segment', 'gap', 'file_count', 'classification', 'approval', 'missing_artifact', 'wrong_bytes', 'record_ref'])
def test_tampered_packages_rollback(tmp_path, bundle, inspection, change):
    package = build_candidate_package(inspection)
    body = package.report()
    artifacts = list(package.artifacts)
    if change == 'omitted_segment': body['segments'].pop()
    if change == 'gap': body['segments'][0]['start_byte'] = 1
    if change == 'file_count': body['file_count'] -= 1
    if change == 'classification': body['segments'][0]['classification'] = 'PUBLISHED_CLAIM'
    if change == 'approval': body['scientific_assessment'] = 'APPROVED'
    if change == 'record_ref':
        body['record_refs'] = [{'record_type': 'agtxiv.v3.claim/0.0.0', 'record_id': 'claim:absent', 'revision': 1, 'content_hash': 'sha256:' + '0' * 64}]
    if change in {'missing_artifact', 'wrong_bytes'}:
        identifier = body['files'][0]['artifact']['artifact_id']
        artifacts = [a for a in artifacts if a.artifact_id != identifier]
        if change == 'wrong_bytes': artifacts.append(SuppliedArtifact(identifier, body['files'][0]['artifact']['media_type'], b'wrong'))
    artifact = _artifact(canonical(body), 'application/json')
    artifacts = [a for a in artifacts if a.artifact_id != package.artifact.artifact_id] + [artifact]
    bad = CandidatePackage(artifact, tuple(artifacts))
    with LocalStore(tmp_path / 'db', bundle) as store:
        with pytest.raises((ContractError, SourceError)):
            persist_candidate_package(store, bad)
        assert store._db.execute('SELECT count(*) FROM artifacts').fetchone() == (0,)


def test_real_pinned_robustness_whole_directory(tmp_path, bundle):
    root = ROOT / 'Reference/Application of a resource theory for magic states to fault-tolerant quantum computing'
    main = 'Robustness_main_appendix.tex'
    inspection = inspect_source_directory(root, main)
    original = inspection.sources[main]
    assert len(original) == 56170
    assert hashlib.sha256(original).hexdigest() == '48adf581a5f8353bb1125c75b8e0a075ff7ba79917f2a12d9f7e0f4ad1a8312d'
    with tarfile.open(fileobj=io.BytesIO(inspection.sources['source.tar'])) as archive:
        members = [m for m in archive.getmembers() if m.isfile()]
        assert len(members) == 5
        names = set()
        for member in members:
            name = member.name.removeprefix('./')
            names.add(name)
            assert archive.extractfile(member).read() == inspection.sources[name]
    originals = names | {'source.tar'}
    assert len(originals) == 6
    assert all(p.startswith('build/') for p in inspection.sources.keys() - originals)
    from agtxiv_v3.candidates import build_local_proposed_context, build_interpretation_records
    from agtxiv_v3.contracts import RecordSet, exact_ref, kind
    from agtxiv_v3.dependencies import inspect_dependencies
    context = build_local_proposed_context(inspection, bundle=bundle,
        corpus_bytes=(ROOT / 'schema v0.0/evaluation-corpus.json').read_bytes())
    records = (context['source_snapshot'], context['paper_structure'], *build_interpretation_records(
        inspection, robustness_proposals(inspection), source_snapshot=context['source_snapshot'],
        bundle=bundle, producer=context['producer'], policy_ref=context['policy_ref'], created_at=context['created_at']))
    kwargs = dict(proposals=robustness_proposals(inspection), open_questions=ROBUSTNESS_QUESTIONS,
                  records=records, supporting_artifacts=context['artifacts'])
    package = build_candidate_package(inspection, **kwargs)
    assert all(not bundle.validate_record(r) for r in (*records, *context['context_records']))
    policy = context['context_records'][0]
    assert policy['payload']['charter_state'] == 'PROPOSED'
    assert policy['payload']['allowed_principal_ids'] == []
    assert policy['payload']['ratification_commit'] is None
    assert context['source_snapshot']['payload']['missing_material']
    assert all(r['producer']['identity_assurance'] == 'DECLARED' for r in records)
    nodes = {p['id']: r for p, r in zip(robustness_proposals(inspection), [r for r in records if kind(r) == 'argument-node'])}
    record_set = RecordSet(bundle, (*context['context_records'], *records), package.artifacts)
    assert record_set.validate(require_artifacts=True).valid
    for trigger in ('definition', 'channel'):
        impact = inspect_dependencies(record_set, [exact_ref(nodes[trigger])])
        assert exact_ref(nodes['R3']) in [a['target_ref'] for a in impact.payload['affected']]
        assert exact_ref(nodes['postselection']) not in [a['target_ref'] for a in impact.payload['affected']]
    obligations = package.report()['proposed_obligations']
    assert obligations and all(o['state'] == 'OPEN' and o['disposition'] == 'DEFERRED' and not o['performed'] for o in obligations)
    assert all(o['frozen_scope_ref'] is None and o['evidence_refs'] == [] for o in obligations)
    assert all(o['target_refs'] or o['source_artifact_refs'] for o in obligations)
    inventory = package.report()['candidate_inventory']
    assert inventory['semantic_claim_denominator'] is None
    assert inventory['main_line_count'] == 548
    assert sum(inventory['main_bucket_counts'].values()) == 548
    assert all(inventory['main_bucket_counts'].values())
    assert package.report()['file_count'] == len(inspection.sources)
    assert len(package.report()['segments']) >= 548
    assert package == build_candidate_package(inspection, **kwargs)
    with LocalStore(tmp_path / 'real.sqlite', bundle) as store:
        assert persist_candidate_package(store, package, context_records=context['context_records']).valid
    with LocalStore(tmp_path / 'real.sqlite', bundle, readonly=True) as store:
        result = query_candidate_package(store, package.reference())
        proposals = {p['id']: p for p in result['package']['proposals']}
        anchor = proposals['R3']['anchors'][0]
        assert original[anchor['start_byte']:anchor['end_byte']].startswith(b'    \\item[R3]')
        assert proposals['postselection']['dependencies'] == []
        assert 'R3' not in proposals['postselection']['dependencies']
        assert all(p['verification'] == 'UNVERIFIED' for p in proposals.values())
    assert (root / main).read_bytes() == original


def test_cli_build_query_and_no_overwrite(tmp_path, inspection):
    command = [sys.executable, str(ROOT / 'tools/inspect_v3_candidates.py')]
    output, database = tmp_path / 'result.json', tmp_path / 'db'
    build = command + ['build', str(inspection.root), '--main', 'main.tex', '--output', str(output), '--database', str(database)]
    result = subprocess.run(build, capture_output=True)
    assert result.returncode == 0, result.stderr
    before = output.read_bytes()
    assert subprocess.run(build, capture_output=True).returncode == 2
    assert output.read_bytes() == before
    query = subprocess.run(command + ['query', '--database', str(database), '--reference', str(output)], capture_output=True)
    assert query.returncode == 0, query.stderr
    assert b'PROVISIONAL' in query.stdout
    forbidden = subprocess.run(command + ['build', str(inspection.root), '--main', 'main.tex', '--output', str(inspection.root / 'output.json')], capture_output=True)
    assert forbidden.returncode == 2
    assert not (inspection.root / 'output.json').exists()


def test_existing_contract_projection_requires_real_caller_context(tmp_path, bundle, inspection):
    from agtxiv_v3.candidates import build_interpretation_records
    from agtxiv_v3.contracts import exact_ref
    from agtxiv_v3.intake import build_source_candidates
    from test_contracts import FixtureGraph
    from test_intake import caller_metadata
    graph = FixtureGraph(bundle)
    metadata = caller_metadata(bundle)
    metadata['policy_ref'] = exact_ref(graph.policy)
    source = build_source_candidates(inspection, **metadata)
    proposals = [proposal(inspection)]
    second = copy.deepcopy(proposals[0])
    second.update(id='dependent', dependencies=['candidate'])
    proposals.append(second)
    kwargs = dict(source_snapshot=source.source_snapshot, bundle=bundle,
                  producer=metadata['producer'], policy_ref=metadata['policy_ref'], created_at=metadata['created_at'])
    records = build_interpretation_records(inspection, proposals, **kwargs)
    assert records == build_interpretation_records(inspection, proposals, **kwargs)
    assert all(not bundle.validate_record(r) for r in records)
    assert {r['record_type'].split('/')[-2].split('.')[-1] for r in records} == {
        'source-span', 'argument-node', 'inference-step', 'frontier-item', 'dependency-binding'}
    package = build_candidate_package(inspection, proposals=proposals,
        records=(source.source_snapshot, source.paper_structure, *records), supporting_artifacts=source.artifacts)
    with LocalStore(tmp_path / 'records.db', bundle) as store:
        assert persist_candidate_package(store, package, context_records=[graph.policy]).valid
    with LocalStore(tmp_path / 'records.db', bundle, readonly=True) as store:
        result = query_candidate_package(store, package.reference())
        assert len(result['records']) == len(records) + 2
        assert all(r['payload']['state'] == 'OPEN' for r in result['records'] if 'frontier-item' in r['record_type'])
    with pytest.raises(SourceError):
        build_candidate_package(inspection, records=[graph.policy])
    omitted = copy.deepcopy(source.source_snapshot)
    omitted['payload']['units'].pop()
    from agtxiv_v3.contracts import content_hash
    omitted['content_hash'] = content_hash(omitted)
    with pytest.raises(SourceError, match='omits'):
        build_interpretation_records(inspection, proposals, **{**kwargs, 'source_snapshot': omitted})


@pytest.mark.parametrize('line,bucket,cue', [
    (b'\\begin{theorem}', 'TENTATIVE_CLAIM_CUE', 'THEOREM_PROPERTY'),
    (b'\\item[R3] Monotonicity', 'TENTATIVE_CLAIM_CUE', 'ENUMERATED_ASSERTION'),
    (b'We show a result.', 'TENTATIVE_CLAIM_CUE', 'VERBAL_ASSERTION'),
    (b'$x = 1.23$', 'TENTATIVE_CLAIM_CUE', 'NUMERICAL'),
    (b'\\begin{tabular}{cc}', 'TENTATIVE_CLAIM_CUE', 'TABLE'),
    (b'$x=y$', 'TENTATIVE_CLAIM_CUE', 'EQUATION'),
    (b'% theorem in a comment', 'NONCLAIM_CUE', 'BLANK_OR_LEXICAL_COMMENT'),
    (b'ordinary undecided prose', 'UNKNOWN_TEXT', None),
])
def test_tentative_lexical_cues_are_not_observed_scientific_claims(line, bucket, cue):
    from agtxiv_v3.candidates import _candidate_cues
    result = _candidate_cues(line)
    assert result['bucket'] == bucket
    if cue:
        assert cue in result['cues']
    assert result['authority_status'] == 'ORACLE_PROPOSED'
    assert result['verification'] == 'UNVERIFIED'


def test_real_cli_explicit_unadopted_context_and_known_observation_replay(tmp_path):
    from agtxiv_v3.contracts import parse
    root = ROOT / 'Reference/Application of a resource theory for magic states to fault-tolerant quantum computing'
    main = 'Robustness_main_appendix.tex'
    command = [sys.executable, str(ROOT / 'tools/inspect_v3_candidates.py'), 'build', str(root),
               '--main', main, '--robustness', '--local-proposed-context', '--database', str(tmp_path / 'real.db')]
    first, second = tmp_path / 'first.json', tmp_path / 'second.json'
    result = subprocess.run(command + ['--output', str(first)], capture_output=True)
    assert result.returncode == 0, result.stderr
    body = parse(first.read_bytes())
    source = next(r for r in body['records'] if 'source-snapshot' in r['record_type'])
    observed_at = source['payload']['acquired_at']
    result = subprocess.run(command + ['--observed-at', observed_at, '--output', str(second)], capture_output=True)
    assert result.returncode == 0, result.stderr
    assert first.read_bytes() == second.read_bytes()
    assert len(body['records']) == 35
    assert len(body['context_records']) == 1
    assert body['context_records'][0]['payload']['allowed_principal_ids'] == []
    assert source['payload']['paper_id'] == 'arxiv:1609.07488v2'
    assert source['payload']['acquisition_method'] == 'LOCAL_IMPORT'
    assert source['payload']['rights_status'] == 'UNRESOLVED'
    query = subprocess.run([sys.executable, str(ROOT / 'tools/inspect_v3_candidates.py'), 'query',
        '--database', str(tmp_path / 'real.db'), '--reference', str(first)], capture_output=True)
    assert query.returncode == 0, query.stderr
    result = parse(query.stdout)
    assert result['mode'] == 'PROVISIONAL'
    assert result['records'] == body['records']
    assert result['package']['source_bytes_sha256'] == body['package']['source_bytes_sha256']


def test_segment_amplification_rejected_before_candidate_list_allocation(tmp_path, monkeypatch):
    import agtxiv_v3.candidates as candidates
    root = tmp_path / 'many-lines'
    root.mkdir()
    (root / 'main.tex').write_bytes(b'\n' * 20000)
    inspection = inspect_source_directory(root, 'main.tex')
    def no_classification_before_preflight(*args):
        pytest.fail('Segment objects must not be built before the whole segment budget is checked')
    monkeypatch.setattr(candidates, '_candidate_cues', no_classification_before_preflight)
    with pytest.raises(SourceError, match='segment limit'):
        build_candidate_package(inspection)


def test_package_and_query_byte_budgets_fail_before_publication(tmp_path, bundle, inspection, monkeypatch):
    import agtxiv_v3.candidates as candidates
    with monkeypatch.context() as patch:
        patch.setattr(candidates, 'MAX_PACKAGE_BYTES', 1000)
        with pytest.raises(SourceError, match='byte budget'):
            build_candidate_package(inspection)
    with monkeypatch.context() as patch:
        patch.setattr(candidates, 'MAX_QUERY_BYTES', 1000)
        package = build_candidate_package(inspection)
        with LocalStore(tmp_path / 'small-query.db', bundle) as store:
            with pytest.raises(SourceError, match='byte budget'):
                persist_candidate_package(store, package)
            assert store._db.execute('SELECT count(*) FROM artifacts').fetchone() == (0,)
            assert store.ingest((), package.artifacts).valid
            with pytest.raises(SourceError, match='byte budget'):
                query_candidate_package(store, package.reference())


def test_reader_caps_raw_package_before_parsing_at_persist_and_query(tmp_path, bundle, monkeypatch):
    import agtxiv_v3.candidates as candidates
    huge = _artifact(b' ' * (candidates.MAX_PACKAGE_BYTES + 1), 'application/json')
    package = CandidatePackage(huge, (huge,))
    with LocalStore(tmp_path / 'oversize.db', bundle) as store:
        with pytest.raises(SourceError, match='byte budget'):
            persist_candidate_package(store, package)
        assert store._db.execute('SELECT count(*) FROM artifacts').fetchone() == (0,)
        assert store.ingest((), [huge]).valid
        def forbidden_parse(*args):
            pytest.fail('Oversized package reached the JSON parser')
        monkeypatch.setattr(candidates, 'parse', forbidden_parse)
        with pytest.raises(SourceError, match='byte budget'):
            query_candidate_package(store, huge.reference())


@pytest.mark.parametrize('limit', ['max_file_bytes', 'max_path_bytes', 'max_depth', 'max_entries'])
def test_manifest_checkable_limits_rechecked_at_persist_and_historical_query(tmp_path, bundle, limit):
    root = tmp_path / 'manifest'
    (root / 'a/b').mkdir(parents=True)
    (root / 'main.tex').write_bytes(b'hello')
    (root / 'a/b/deep').write_bytes(b'hello')
    inspection = inspect_source_directory(root, 'main.tex')
    package = build_candidate_package(inspection)
    body = package.report()
    body['limits'][limit] = 1
    artifact = _artifact(canonical(body), 'application/json')
    artifacts = tuple(a for a in package.artifacts if a != package.artifact) + (artifact,)
    bad = CandidatePackage(artifact, artifacts)
    with LocalStore(tmp_path / 'manifest.db', bundle) as store:
        with pytest.raises(SourceError):
            persist_candidate_package(store, bad)
        assert store._db.execute('SELECT count(*) FROM artifacts').fetchone() == (0,)
        assert store.ingest((), artifacts).valid
        with pytest.raises(SourceError):
            query_candidate_package(store, bad.reference())
    assert 'empty directories' in package.report()['filesystem_limit_verification']


def test_generic_local_context_rejects_basename_without_corpus_main_hash(tmp_path, bundle):
    from agtxiv_v3.candidates import build_local_proposed_context
    main = 'Thesis.tex'  # Another corpus paper: no robustness-specific guard.
    (tmp_path / main).write_bytes(b'Wrong bytes using an existing corpus basename.')
    inspection = inspect_source_directory(tmp_path, main)
    with pytest.raises(SourceError, match='corpus-pinned canonical main'):
        build_local_proposed_context(inspection, bundle=bundle,
            corpus_bytes=(ROOT / 'schema v0.0/evaluation-corpus.json').read_bytes())
